# Generated by Django 6.0.4 on 2026-05-05 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
        ('scolarite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('filiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='scolarite.filiere')),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant_data', to='authentification.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(blank=True, max_length=100)),
                ('matieres', models.ManyToManyField(related_name='professeurs', to='scolarite.matiere')),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professeur_data', to='authentification.profil')),
            ],
        ),
    ]
