# Generated by Django 6.0.4 on 2026-05-05 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarite', '0002_etudiant_professeur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('matiere', models.CharField(max_length=100)),
                ('justifiee', models.BooleanField(default=False)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(limit_choices_to={'profil__role': 'ETUDIANT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
