# Generated by Django 6.0.4 on 2026-05-06 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarite', '0003_absence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='commentaire',
        ),
        migrations.AddField(
            model_name='absence',
            name='seance',
            field=models.CharField(default='Matin', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='absence',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='absence',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
