# Generated by Django 6.0.5 on 2026-05-07 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarite', '0004_remove_absence_commentaire_absence_seance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeanceCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('LUN', 'Lundi'), ('MAR', 'Mardi'), ('MER', 'Mercredi'), ('JEU', 'Jeudi'), ('VEN', 'Vendredi'), ('SAM', 'Samedi')], max_length=3)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('salle', models.CharField(max_length=50)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolarite.matiere')),
            ],
        ),
    ]
